### ISSUE TITLE
Fatal error on php 7.2!

### ISSUE THREAD

**Issue by ben72** [Billmate/woocommerce#258]
1. Update to php 7.2
2. Go to checkout
3. Click button to get address from ssn.
Now you get the fatal error seen below. Checking out does not work either!

`
[02-Nov-2018 12:50:35 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function mb_convert_encoding() in /home/ekoinsik/public_html/lotuseco/wp-content/plugins/billmate-payment-gateway-for-woocommerce/class-billmate-common.php:141
Stack trace:
#0 /home/ekoinsik/public_html/lotuseco/wp-includes/class-wp-hook.php(286): BillmateCommon->getaddress('')
#1 /home/ekoinsik/public_html/lotuseco/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /home/ekoinsik/public_html/lotuseco/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /home/ekoinsik/public_html/lotuseco/wp-admin/admin-ajax.php(100): do_action('wp_ajax_getaddr...')
#4 {main}
  thrown in /home/ekoinsik/public_html/lotuseco/wp-content/plugins/billmate-payment-gateway-for-woocommerce/class-billmate-common.php on line 141
`

**Comment by ben72** [comment]
This worked when I enabled mbstring in php extensions. That extension was not selected by default for php 7.2! In php 7.1 it was enabled by default.
